### ISSUE TITLE
Timers cannot be started from another thread

### ISSUE THREAD

**Issue by RomanZhilich** [rinaldus/mail-notifier#2]
I'm using mail-notifier on OS X from terminal and output gets bloated with this message:

```
Object::startTimer: Timers cannot be started from another thread
```

That seems pretty weird, since timer started in the same place it's created. Moreover, if I understand correctly it should only be started once with QThread.
It seems that message appears once for every mail check performed.

**Comment by rinaldus** [comment]
Please specify, you see this warning every N minutes when it checks mail automatically or you also see warning when you check mail manually clicking "Context menu -> Check now"?

**Comment by RomanZhilich** [comment]
"Context menu -> Check now" doesn't cause message to appear, only scheduled check.

**Comment by rinaldus** [comment]
I rewrote periodically mail check function. This code seems to work in Linux properly, but unfortunately I have not OS X to test it there. There are differences between Linux and OS X, because I don't see any warnings and errors in Linux terminal. I attached modified version. Please, test it. Since Github doesn't accept attachments with py extension, download my attachment, rename it to mail-notifier.py and copy it to your mail-notifier installation folder. Then tell me if this modified version works properly or not. If it work, I will commit it and close bug.

[mail-notifier.txt](https://github.com/rinaldus/mail-notifier/files/104604/mail-notifier.txt)

**Comment by RomanZhilich** [comment]
Thanks, I'll test it shortly.

P.S. Don't you think it would be more convenient to push your changes in separate branch?

**Comment by rinaldus** [comment]
No, I don't think, that this bug fix needs to push in separate branch. It seems, I wrote my initial periodical mail check function not quite correctly. This was passed by Linux, but in other platform there were issues, that I didn't know. I hope this function will work correctly in all platforms.
However, when I will start to add new features in program, I'm planning to do it in separate development branch to prevent making program unworkable.

**Comment by RomanZhilich** [comment]
Well I just tested it and message seems to be gone now.

> I don't think, that this bug fix needs to push in separate branch

I only meant that it would be more convenient to make changes and test. IMHO

**Comment by rinaldus** [comment]
Thank you for your help!
